name: ATempFly
version: '${version}'
main: fr.ardidex.atempfly.ATempFly
softdepend: [ SuperiorSkyblock2, PlaceholderAPI, Factions]
authors: [ ardidex ]
description: a tempfly plugin
commands:
  tf:
    description: temp fly
    aliases:
      - tfly
      - atempfly